#!/usr/bin/env bash

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
  wget https://github.com/dandavison/delta/releases/download/0.18.2/git-delta_0.18.2_arm64.deb
  sudo dpkg -i git-delta_0.18.2_arm64.deb
  rm git-delta_0.18.2_arm64.deb
  
  sudo apt -y install tldr ripgrep
fi

