#!/usr/bin/env bash

# Backup existing .zshrc
# if [ -f ~/.zshrc ]; then
#     mv ~/.zshrc ~/.zshrc.bak
# fi

rm -rf  ~/.oh-my-zsh
# if [ ! -d ~/.oh-my-zsh ]; then
echo "Installing Oh My Zsh..."
# wget -qO- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | zsh || true
curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | zsh || true

# else
    # echo "Oh My Zsh already installed."
# fi

# Install Zsh plugins
ZSH_CUSTOM=${ZSH_CUSTOM:-~/.oh-my-zsh/custom}
mkdir -p "$ZSH_CUSTOM/plugins"

if [ ! -d "$ZSH_CUSTOM/plugins/zsh-autosuggestions" ]; then
    git clone --depth=1 https://github.com/zsh-users/zsh-autosuggestions "$ZSH_CUSTOM/plugins/zsh-autosuggestions"
fi

if [ ! -d "$ZSH_CUSTOM/plugins/zsh-syntax-highlighting" ]; then
    git clone --depth=1 https://github.com/zsh-users/zsh-syntax-highlighting "$ZSH_CUSTOM/plugins/zsh-syntax-highlighting"
fi

# Install Zsh-in-Docker with Agnoster theme
# sudo sh -c "$(wget -O- https://raw.githubusercontent.com/deluan/zsh-in-docker/master/zsh-in-docker.sh)" -- -t agnoster
sudo sh -c "$(curl -fsSL https://raw.githubusercontent.com/deluan/zsh-in-docker/master/zsh-in-docker.sh)" -- -t agnoster

# Restore .zshrc backup
# if [ -f ~/.zshrc.bak ]; then
#     mv ~/.zshrc.bak ~/.zshrc
# fi

# Set theme to Agnoster in .zshrc
sed -i '' 's/^ZSH_THEME=.*/ZSH_THEME="agnoster"/' ~/.zshrc

# Install Zsh Autocomplete
if [ ! -d ~/zsh-autocomplete ]; then
    git clone --depth 1 https://github.com/marlonrichert/zsh-autocomplete.git ~/zsh-autocomplete
fi

# Add Zsh autocomplete configuration
if ! grep -q "zsh-autocomplete" ~/.zshrc; then
    echo 'source ~/zsh-autocomplete/zsh-autocomplete.plugin.zsh' >> ~/.zshrc
    echo "skip_global_compinit=1" >> ~/.zshenv
fi


# Git aliases
# cat <<EOF >> ~/.zshrc


# # Git Aliases
# alias gp="git pull"
# alias gs="git status"
# alias gb="git branch"
# alias gc="git checkout"
# alias gbclean="git branch | grep -v \"develop.*\|master\|hotfix\|release\|main\" | xargs git branch -D"

# # AWS & Kafka Aliases
# alias saml="saml2aws login -a dev -p dev --session-duration=38800"
# alias kafka-sink-monitor="~/dotfiles/kafka-sink-monitor.sh"
# alias kafka-sink-avg-lag="~/dotfiles/kafka-sink-avg-lag.sh"
# alias kafka-sink-task="~/dotfiles/kafka-sink-task.sh"
# alias kafka-clear-topic="~/dotfiles/kafka-clear-topic.sh"
# alias awslogin="aws sso login --sso-session sso"

# EOF

cp $DEV_ENV/dotfiles/env/config/.zshenv ~/.zshenv
cp $DEV_ENV/dotfiles/env/config/.zshrc ~/.zshrc

# Change default shell to Zsh
if [ "$(basename "$SHELL")" != "zsh" ]; then
    echo "Changing default shell to Zsh..."
    sudo chsh -s "$(which zsh)" "$(whoami)"
fi
